use_frameworks!
platform :ios, '9.0'

target 'Overlays_Example' do
  pod 'Overlays', :path => '../'
  pod 'MBProgressHUD', '1.1.0'

  target 'Overlays_Tests' do
    inherit! :search_paths

    
  end
end
